#!/usr/bin/env python3
"""
Generate orbit.dat reference file using the standard (CPython) sgp4 package.

Propagates the ISS TLE at 60-second intervals over 24 hours and writes
each sample as a line:

    unix_timestamp t_min_since_epoch lat_deg lon_deg alt_km x_eci y_eci z_eci gmst_rad

This file is consumed by test_propagate_accuracy.py to validate the
micropython propagators against a known-good reference.
"""

import math
import os
import sys
from datetime import datetime, timezone, timedelta

from sgp4.api import Satrec, WGS72
from sgp4.earth_gravity import wgs72

# --- ISS TLE (fetched 2026-02-15) ---
TLE_NAME = "ISS (ZARYA)"
TLE_LINE1 = "1 25544U 98067A   26046.56961129  .00012237  00000+0  23255-3 0  9991"
TLE_LINE2 = "2 25544  51.6318 181.6982 0010992 101.7612 258.4610 15.48625638552905"

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_FILE = os.path.join(OUT_DIR, "orbit.dat")

# Propagation window
INTERVAL_SEC = 60        # 1-minute samples
DURATION_SEC = 24 * 3600 # 24 hours


def gmst_from_jd(jd):
    """Greenwich Mean Sidereal Time from Julian Date (radians).
    Uses the IAU 1982 formula (same basis as the micropython code)."""
    T = (jd - 2451545.0) / 36525.0
    gmst_deg = (280.46061837
                + 360.98564736629 * (jd - 2451545.0)
                + 0.000387933 * T * T
                - T * T * T / 38710000.0) % 360.0
    return math.radians(gmst_deg)


def eci_to_geodetic(x, y, z, gmst):
    """Convert ECI (km) to geodetic (lat_deg, lon_deg, alt_km) using WGS-84."""
    # ECEF
    cos_g = math.cos(gmst)
    sin_g = math.sin(gmst)
    x_ecef = cos_g * x + sin_g * y
    y_ecef = -sin_g * x + cos_g * y
    z_ecef = z

    # Geodetic (iterative)
    a = 6378.137
    f = 1.0 / 298.257223563
    e2 = 2 * f - f * f
    p = math.sqrt(x_ecef ** 2 + y_ecef ** 2)
    lon = math.atan2(y_ecef, x_ecef)
    lat = math.atan2(z_ecef, p * (1.0 - e2))

    for _ in range(10):
        sin_lat = math.sin(lat)
        N = a / math.sqrt(1.0 - e2 * sin_lat * sin_lat)
        alt = p / math.cos(lat) - N
        lat = math.atan2(z_ecef, p * (1.0 - e2 * N / (N + alt)))

    sin_lat = math.sin(lat)
    N = a / math.sqrt(1.0 - e2 * sin_lat * sin_lat)
    alt = p / math.cos(lat) - N

    return math.degrees(lat), math.degrees(lon), alt


def jd_from_unix(unix_ts):
    """Julian Date from Unix timestamp."""
    return unix_ts / 86400.0 + 2440587.5


def main():
    sat = Satrec.twoline2rv(TLE_LINE1, TLE_LINE2, WGS72)

    # TLE epoch as a Unix timestamp
    # sgp4 stores epoch as jdsatepoch + jdsatepochF (integer + fractional JD)
    epoch_jd = sat.jdsatepoch + sat.jdsatepochF
    epoch_unix = (epoch_jd - 2440587.5) * 86400.0

    # Start propagation at epoch
    start_unix = int(epoch_unix)

    samples = []
    n_samples = DURATION_SEC // INTERVAL_SEC + 1

    for i in range(n_samples):
        unix_ts = start_unix + i * INTERVAL_SEC
        t_min = (unix_ts - epoch_unix) / 60.0

        # Standard SGP4 propagation (returns km and km/s)
        jd_int = int(unix_ts // 86400) + 2440587
        jd_frac = (unix_ts % 86400) / 86400.0 + 0.5
        if jd_frac >= 1.0:
            jd_int += 1
            jd_frac -= 1.0

        e, r, v = sat.sgp4(jd_int, jd_frac)
        if e != 0:
            print(f"SGP4 error code {e} at t_min={t_min:.1f}, skipping")
            continue

        x_eci, y_eci, z_eci = r  # km

        jd = jd_int + jd_frac
        gmst = gmst_from_jd(jd)
        lat, lon, alt = eci_to_geodetic(x_eci, y_eci, z_eci, gmst)

        samples.append((unix_ts, t_min, lat, lon, alt,
                         x_eci, y_eci, z_eci, gmst))

    # Write output
    with open(OUT_FILE, 'w') as f:
        # Header
        f.write(f"# ISS orbit reference data — generated by CPython sgp4 {Satrec.__module__}\n")
        f.write(f"# TLE: {TLE_LINE1}\n")
        f.write(f"#       {TLE_LINE2}\n")
        f.write(f"# Epoch unix: {epoch_unix:.3f}   Samples: {len(samples)}  "
                f"Interval: {INTERVAL_SEC}s  Duration: {DURATION_SEC}s\n")
        f.write("# unix_ts  t_min  lat_deg  lon_deg  alt_km  "
                "x_eci_km  y_eci_km  z_eci_km  gmst_rad\n")

        for row in samples:
            f.write(f"{row[0]}  {row[1]:.6f}  {row[2]:.8f}  {row[3]:.8f}  "
                    f"{row[4]:.6f}  {row[5]:.6f}  {row[6]:.6f}  "
                    f"{row[7]:.6f}  {row[8]:.10f}\n")

    print(f"Wrote {len(samples)} samples to {OUT_FILE}")
    print(f"  Epoch unix : {epoch_unix:.3f}")
    print(f"  Time range : {start_unix} .. {start_unix + DURATION_SEC}")
    print(f"  First row  : t_min={samples[0][1]:.2f}  lat={samples[0][2]:.4f}  lon={samples[0][3]:.4f}")
    print(f"  Last row   : t_min={samples[-1][1]:.2f}  lat={samples[-1][2]:.4f}  lon={samples[-1][3]:.4f}")


if __name__ == "__main__":
    main()
