#!/usr/bin/env python3
"""
Accuracy test: compare micropython propagators against CPython reference SGP4.

Reads orbit.dat (generated by generate_orbit_dat.py) and runs both:
  1. micropython sgp4.py  → ECI, lat/lon/alt via satellite_position.py
  2. propagate.MicroSGP4  → aov_deg, eqx_deg, lat, lon

Reports max errors in:
  - Latitude  (degrees)
  - Longitude (degrees)
  - Altitude  (km)
  - 3-D ECI separation (km)
  - AoV / EQX motor angles (degrees) — micro sgp4 vs reference

Run:
    python -m pytest micropython/tests/test_propagate_accuracy.py -v -s
    python micropython/tests/test_propagate_accuracy.py
"""

import math
import os
import sys
import time

# Force UTC — satellite_position.py uses time.mktime() which is UTC on
# MicroPython but local-time on CPython.  Without this, lat/lon errors
# are offset by the host's timezone.
os.environ['TZ'] = 'UTC'
if hasattr(time, 'tzset'):
    time.tzset()

# Add micropython/ to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from sgp4 import SGP4 as MicroSGP4Model
import satellite_position
import propagate

DAT_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "orbit.dat")

# TLE parameters — must match what generate_orbit_dat.py used
TLE_LINE1 = "1 25544U 98067A   26046.56961129  .00012237  00000+0  23255-3 0  9991"
TLE_LINE2 = "2 25544  51.6318 181.6982 0010992 101.7612 258.4610 15.48625638552905"


def parse_tle():
    """Parse TLE lines into SGP4 init parameters (same logic as modes.py)."""
    line1, line2 = TLE_LINE1, TLE_LINE2

    # Epoch
    epoch_str = line1[18:32].strip()
    epoch_year = int(epoch_str[:2])
    epoch_day = float(epoch_str[2:])

    bstar_mantissa = line1[53:59].strip()
    bstar_exp = line1[59:61].strip()
    bstar = float(bstar_mantissa) * 10.0 ** float(bstar_exp)

    inc = float(line2[8:16])
    raan = float(line2[17:25])
    ecc = float('0.' + line2[26:33])
    argp = float(line2[34:42])
    ma = float(line2[43:51])
    n = float(line2[52:63])

    return epoch_year, epoch_day, bstar, inc, raan, ecc, argp, ma, n


def load_reference():
    """Load orbit.dat into list of dicts."""
    rows = []
    with open(DAT_FILE) as f:
        for line in f:
            if line.startswith('#'):
                continue
            parts = line.split()
            if len(parts) < 9:
                continue
            rows.append({
                'unix_ts': int(parts[0]),
                't_min': float(parts[1]),
                'lat': float(parts[2]),
                'lon': float(parts[3]),
                'alt': float(parts[4]),
                'x_eci': float(parts[5]),
                'y_eci': float(parts[6]),
                'z_eci': float(parts[7]),
                'gmst': float(parts[8]),
            })
    return rows


def angle_diff(a, b):
    """Signed shortest-path angular difference in degrees."""
    d = (a - b) % 360.0
    if d > 180.0:
        d -= 360.0
    return d


def run_accuracy_test():
    """Main accuracy comparison."""
    if not os.path.exists(DAT_FILE):
        print("orbit.dat not found — run generate_orbit_dat.py first")
        sys.exit(1)

    ref = load_reference()
    print(f"Loaded {len(ref)} reference samples from orbit.dat")

    # --- Initialize micropython SGP4 ---
    params = parse_tle()
    epoch_year, epoch_day = params[0], params[1]

    micro_sgp4 = MicroSGP4Model()
    micro_sgp4.init(*params)

    # --- Initialize MicroSGP4 propagator ---
    micro_prop = propagate.MicroSGP4(micro_sgp4)

    # --- Accumulators ---
    # Raw sgp4.py ECI comparison
    max_eci_sep = 0.0
    max_eci_sep_tmin = 0.0
    sum_eci_sep = 0.0

    # satellite_position.py geodetic comparison
    max_lat_err = 0.0
    max_lon_err = 0.0
    max_alt_err = 0.0
    max_lat_tmin = 0.0
    max_lon_tmin = 0.0
    max_alt_tmin = 0.0

    # propagate.MicroSGP4 aov/eqx comparison
    # (We compute reference aov/eqx from the reference data's orbital elements)
    max_aov_err = 0.0
    max_eqx_err = 0.0
    max_aov_tmin = 0.0
    max_eqx_tmin = 0.0

    n = 0
    for row in ref:
        t_min = row['t_min']
        unix_ts = row['unix_ts']

        # ============================================================
        # 1. Raw ECI from micropython sgp4.py
        # ============================================================
        x, y, z = micro_sgp4.propagate(t_min)
        # sgp4.py returns ECI in km (already scaled by XKMPER)

        dx = x - row['x_eci']
        dy = y - row['y_eci']
        dz = z - row['z_eci']
        sep = math.sqrt(dx * dx + dy * dy + dz * dz)
        sum_eci_sep += sep
        if sep > max_eci_sep:
            max_eci_sep = sep
            max_eci_sep_tmin = t_min

        # ============================================================
        # 2. satellite_position.py geodetic
        # ============================================================
        t_struct = time.gmtime(unix_ts)
        t_tuple = (t_struct[0], t_struct[1], t_struct[2],
                   t_struct[3], t_struct[4], t_struct[5], 0, 0, 0)

        geo = satellite_position.compute_satellite_geodetic(
            micro_sgp4, epoch_year, epoch_day, t_tuple
        )

        lat_err = abs(geo['latitude'] - row['lat'])
        lon_err = abs(angle_diff(geo['longitude'], row['lon']))
        alt_err = abs(geo['altitude'] - row['alt'])

        if lat_err > max_lat_err:
            max_lat_err = lat_err
            max_lat_tmin = t_min
        if lon_err > max_lon_err:
            max_lon_err = lon_err
            max_lon_tmin = t_min
        if alt_err > max_alt_err:
            max_alt_err = alt_err
            max_alt_tmin = t_min

        # ============================================================
        # 3. propagate.MicroSGP4 aov/eqx
        #    Compare against reference-derived aov/eqx.
        #    Reference aov = argument of latitude from reference ECI
        #    Reference eqx = RAAN - GMST (degrees)
        # ============================================================
        micro_result = micro_prop.get_aov_eqx(unix_ts)
        micro_aov = micro_result[0]
        micro_eqx = micro_result[1]

        # Derive reference aov/eqx from the reference sgp4 elements.
        # We do this by propagating our micro_sgp4 (which already ran above)
        # and comparing its aov/eqx to what MicroSGP4 propagator returns.
        # The key check: does propagate.MicroSGP4 correctly read the
        # exposed elements from sgp4.py?  We verify by computing the
        # expected values from the elements directly.
        ref_aov = math.degrees(micro_sgp4._nu + micro_sgp4._argp_curr) % 360.0
        ref_eqx = math.degrees(micro_sgp4._raan_curr - geo['gmst']) % 360.0

        aov_err = abs(angle_diff(micro_aov, ref_aov))
        eqx_err = abs(angle_diff(micro_eqx, ref_eqx))

        if aov_err > max_aov_err:
            max_aov_err = aov_err
            max_aov_tmin = t_min
        if eqx_err > max_eqx_err:
            max_eqx_err = eqx_err
            max_eqx_tmin = t_min

        n += 1

    avg_eci_sep = sum_eci_sep / n if n > 0 else 0

    # ============================================================
    # Report
    # ============================================================
    print()
    print("=" * 70)
    print("  PROPAGATOR ACCURACY REPORT")
    print(f"  ISS TLE, {n} samples over 24h at 60s intervals")
    print("=" * 70)

    print()
    print("--- micropython sgp4.py vs CPython reference SGP4 ---")
    print(f"  Max ECI separation : {max_eci_sep:10.4f} km   (at t_min={max_eci_sep_tmin:.1f})")
    print(f"  Avg ECI separation : {avg_eci_sep:10.4f} km")
    print()
    print("--- satellite_position.py geodetic vs reference ---")
    print(f"  Max latitude error : {max_lat_err:10.6f} deg  (at t_min={max_lat_tmin:.1f})")
    print(f"  Max longitude error: {max_lon_err:10.6f} deg  (at t_min={max_lon_tmin:.1f})")
    print(f"  Max altitude error : {max_alt_err:10.4f} km   (at t_min={max_alt_tmin:.1f})")
    print()
    print("--- propagate.MicroSGP4 motor angles (self-consistency) ---")
    print(f"  Max AoV error      : {max_aov_err:10.6f} deg  (at t_min={max_aov_tmin:.1f})")
    print(f"  Max EQX error      : {max_eqx_err:10.6f} deg  (at t_min={max_eqx_tmin:.1f})")
    print()

    # Overall 3-D position error at max ECI separation
    print("--- Summary ---")
    if max_eci_sep < 50.0:
        print(f"  ECI: GOOD — max {max_eci_sep:.2f} km (< 50 km threshold)")
    elif max_eci_sep < 200.0:
        print(f"  ECI: ACCEPTABLE — max {max_eci_sep:.2f} km (simplified model)")
    else:
        print(f"  ECI: LARGE — max {max_eci_sep:.2f} km (expected for no-drag model over 24h)")

    if max_lat_err < 1.0 and max_lon_err < 1.0:
        print(f"  Geodetic: GOOD — lat < {max_lat_err:.4f} deg, lon < {max_lon_err:.4f} deg")
    else:
        print(f"  Geodetic: lat {max_lat_err:.4f} deg, lon {max_lon_err:.4f} deg")

    if max_aov_err < 0.01 and max_eqx_err < 0.01:
        print(f"  Motor angles: EXCELLENT — self-consistent to < 0.01 deg")
    else:
        print(f"  Motor angles: AoV {max_aov_err:.6f} deg, EQX {max_eqx_err:.6f} deg")

    print("=" * 70)

    return {
        'max_eci_sep_km': max_eci_sep,
        'avg_eci_sep_km': avg_eci_sep,
        'max_lat_err_deg': max_lat_err,
        'max_lon_err_deg': max_lon_err,
        'max_alt_err_km': max_alt_err,
        'max_aov_err_deg': max_aov_err,
        'max_eqx_err_deg': max_eqx_err,
        'n_samples': n,
    }


# ============================================================
# pytest-compatible test class
# ============================================================
import unittest

class TestPropagateAccuracy(unittest.TestCase):
    """Accuracy assertions against the reference data."""

    @classmethod
    def setUpClass(cls):
        cls.results = run_accuracy_test()

    def test_eci_separation_bounded(self):
        """Micro SGP4 ECI error should stay reasonable over 24h.
        No-drag simplified model diverges from full SGP4 — we accept up to
        500 km over 24 hours (ISS loses ~2 km/orbit from drag)."""
        self.assertLess(self.results['max_eci_sep_km'], 500.0,
                        "ECI separation too large — check sgp4.py math")

    def test_latitude_error(self):
        """Latitude should be accurate to within 3 degrees over 24h.
        The simplified model (no drag) drifts ~2 deg by end of window."""
        self.assertLess(self.results['max_lat_err_deg'], 3.0)

    def test_longitude_error(self):
        """Longitude should be accurate to within 3 degrees over 24h."""
        self.assertLess(self.results['max_lon_err_deg'], 3.0)

    def test_altitude_error(self):
        """Altitude should be accurate to within 50 km over 24h."""
        self.assertLess(self.results['max_alt_err_km'], 50.0)

    def test_aov_self_consistent(self):
        """MicroSGP4 propagator aov should exactly match sgp4 exposed elements."""
        self.assertLess(self.results['max_aov_err_deg'], 0.01,
                        "AoV not self-consistent with sgp4 exposed elements")

    def test_eqx_self_consistent(self):
        """MicroSGP4 propagator eqx should exactly match sgp4 exposed elements."""
        self.assertLess(self.results['max_eqx_err_deg'], 0.01,
                        "EQX not self-consistent with sgp4 exposed elements")

    def test_all_samples_processed(self):
        """All reference samples should be processed without error."""
        self.assertGreater(self.results['n_samples'], 1400)


if __name__ == '__main__':
    # When run directly, show the report and then run assertions
    unittest.main(verbosity=2)
